!

diff --git a/.github/workflows/ci-python.yml b/.github/workflows/ci-python.yml
--- a/.github/workflows/ci-python.yml
+++ b/.github/workflows/ci-python.yml
@@ -33,9 +33,6 @@ jobs:
     - run: |
         echo "# Tests results" >> $GITHUB_STEP_SUMMARY
         echo "" >> $GITHUB_STEP_SUMMARY
-        echo "--------------------------" >> $GITHUB_STEP_SUMMARY
-        echo "| Version | Status |" >> $GITHUB_STEP_SUMMARY
-        echo "| ------- | ------ |" >> $GITHUB_STEP_SUMMARY
 
     - name: Set test and source dir in config files
       run: |
@@ -67,8 +64,6 @@ jobs:
         python -m pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-        echo "${{ matrix.python-version }} |" >> $GITHUB_STEP_SUMMARY
-
     - name: Lint with flake8
       run: |
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
@@ -83,11 +78,19 @@ jobs:
     - if: success() || failure()
       name: Update test summary
       run: |
-        if [ $? -eq 0 ]; then
-          echo "✅ ${{ matrix.python-version }} |" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "--------------------------" >> $GITHUB_STEP_SUMMARY
+        echo "### Lint results" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics >> $GITHUB_STEP_SUMMARY || true
+        if git log -1 --pretty=%B | grep -iq "no lint"; then
+          echo "Non-critical lint errors will be treated as warnings due to 'no lint' in commit message"
+          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics >> $GITHUB_STEP_SUMMARY || true
         else
-          echo "❌ ${{ matrix.python-version }} |" >> $GITHUB_STEP_SUMMARY
+          flake8 . --count --select=E --max-complexity=10 --max-line-length=127 --statistics >> $GITHUB_STEP_SUMMARY || true
+          flake8 . --count --exit-zero --select=W --max-complexity=10 --max-line-length=127 --statistics >> $GITHUB_STEP_SUMMARY || true
         fi
+        echo "" >> $GITHUB_STEP_SUMMARY
 
     - name: Test with pytest
       run: |
